🐛 Fix wall bug
AlohaGames/RushTheMusic pull request #107
Opened 2022-01-30 00:29 UTC by youenPlusquellec

Le mur ne stoppe maintenant plus la prochaine partie lancée si on quitte alors que le mur nous stoppe le passage

2022-01-30 00:31 UTC, youenPlusquellec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Relancer le défilement des tuiles si on relance une partie stoppée par des murs](https://trello.com/c/ugbPn421/157-relancer-le-d%C3%A9filement-des-tuiles-si-on-relance-une-partie-stopp%C3%A9e-par-des-murs)

2022-01-31 09:49 UTC, DoBrcd requested changes
Juste une erreur de Lint

2022-01-31 09:49 UTC, DoBrcd commented on Assets/Modules/Enemy/Scripts/Wall.cs
> +            if (isTilesStopped) runAndStopTiles();
Totalement un oublie d'avant mais c'est `RunAndStopTiles()` avec un R majuscule

2022-01-31 12:53 UTC, DoBrcd approved these changes
Go merge

2022-01-31 12:53 UTC, merged