✨ Add boss prefab
AlohaGames/RushTheMusic pull request #108
Opened 2022-02-02 18:57 UTC by youenPlusquellec

2022-02-02 19:55 UTC, youenPlusquellec commented on Assets/Modules/0_Global/Scripts/GameManager.cs
> +        public void Boss()
doc

2022-02-02 19:55 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/Graph/ExperionGraph.cs
> +    /// Graph use by Wyrmling
```suggestion
    /// Graph use by Experion
```

2022-02-02 19:55 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/Nodes/ExperionFireAttack.cs
> +        /// Make the dark wizard fire laser Attack
```suggestion
        /// Make the experion fire laser Attack
```

2022-02-02 19:55 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/Nodes/ExperionIceAttack.cs
> +    /// A Node that make the dark wizard (gameObject) Attack the Hero with an ice laser
```suggestion
    /// A Node that make the experion (gameObject) Attack the Hero with an ice laser
```

2022-02-02 19:55 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/Nodes/ExperionIceAttack.cs
> +        /// Make the dark wizard ice laser Attack
```suggestion
        /// Make the experion ice laser Attack
```

2022-02-02 19:55 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/Nodes/ExperionMove.cs
> +    /// Node that move the wyrmling to the left or the right in a curve movement
```suggestion
    /// Node that move the experion to the left or the right in a curve movement
```

2022-02-02 19:55 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/Nodes/ExperionMove.cs
> +        /// Move the wyrmling Left or Right
```suggestion
        /// Move the experionLeft or Right
```

2022-02-02 19:55 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/Nodes/ExperionMove.cs
> +            // Move the wyrmling
```suggestion
            // Move the experion
```

2022-02-02 19:55 UTC, youenPlusquellec commented on Assets/Modules/Enemy/Scripts/Experion.cs
> +    /// Class for the default lancer
```suggestion
    /// Class for Experion
```

2022-02-02 19:55 UTC, youenPlusquellec commented on Assets/Modules/Enemy/Scripts/Experion.cs
> +        /// Function to bump the lancer
```suggestion
        /// Function to bump experion
```

2022-02-02 23:44 UTC, youenPlusquellec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Prefab Boss](https://trello.com/c/N4qGBVRz/113-prefab-boss)

2022-02-03 16:52 UTC, Enoriz requested changes

2022-02-03 16:52 UTC, Enoriz commented on Assets/Modules/Enemy/Scripts/Assassin.cs
> -        }
??

2022-02-03 16:52 UTC, Enoriz commented on Assets/Modules/Enemy/Scripts/Bat.cs
> -
why?

2022-02-03 16:52 UTC, Enoriz commented on Assets/Modules/Hero/Scripts/Warrior.cs
> +                entity.TakeDamage(damage*5);
x2 ou x3 plutôt?

2022-02-03 16:52 UTC, Enoriz commented on Assets/Modules/UI/Scripts/Bar/SpecificBar/ExperionHealthBar.cs
> +
ligne en trop

2022-02-03 16:52 UTC, Enoriz commented on Assets/Modules/UI/Scripts/Bar/SpecificBar/ExperionHealthBar.cs
> +
ligne en trop

2022-02-03 18:59 UTC, merged