23 inventaire
AlohaGames/RushTheMusic pull request #26
Opened 2021-11-09 10:54 UTC by wilfried7

2021-11-09 11:13 UTC, youenPlusquellec requested changes
Le code en lui même est bon. Juste organiser mieux les tests : 
- Regrouper les lignes qui vont ensemble sans les séparer par des saut de ligne. 
- Commenter bien chaque groupe de lignes
- 1 seul saut de ligne nécessaire entre les paragraphes si tu as bien suivi les étapes du dessus

2021-11-09 11:13 UTC, youenPlusquellec commented on Assets/Tests/PlayMode/Inventory/InventoryTest.cs
> +            // Declaration of an hero
"a Hero"

2021-11-09 11:13 UTC, youenPlusquellec commented on Assets/Tests/PlayMode/Inventory/InventoryTest.cs
> +            Assert.AreEqual(80, hero.currentHealth);
Sur tout le groupe ici, je pense que tu peux regrouper et ne pas mettre de saut de ligne et ajouter un petit commentaire du genre "Check instantiation of the Hero".

Et ne pas oublier de mettre un commentaire à chaque "groupe" de lignes

2021-11-09 11:13 UTC, youenPlusquellec commented on Assets/Tests/PlayMode/Inventory/InventoryTest.cs
> +
Pas besoin de saut de ligne entre le commentaire, la variable et les fonctions

2021-11-09 11:13 UTC, youenPlusquellec commented on Assets/Tests/PlayMode/Inventory/InventoryTest.cs
> +
Pas besoin d'un si gros espace. Un saut de ligne est nécessaire

2021-11-09 11:13 UTC, youenPlusquellec commented on Assets/Tests/PlayMode/Inventory/InventoryTest.cs
> +
1 saut de ligne nécessaire seulement

2021-11-09 11:29 UTC, youenPlusquellec requested changes
Presque parfait 👌

2021-11-09 11:29 UTC, youenPlusquellec commented on Assets/Tests/PlayMode/Inventory/InventoryTest.cs
> +            hero.Init(stats);
Entre l'instanciation et le Init, tu peux mettre un saut de ligne et un commentaire pour éviter de faire trop gros et le diviser un peu plus.

2021-11-09 11:29 UTC, youenPlusquellec commented on Assets/Tests/PlayMode/Inventory/InventoryTest.cs
> +
Enlever 1 ou quelques sauts de lignes entre les gros paragraphes

2021-11-09 15:03 UTC, youenPlusquellec approved these changes

2021-11-10 10:23 UTC, merged

2021-11-10 10:26 UTC, DoBrcd commented
![](https://github.trello.services/images/mini-trello-icon.png) [Gestion de l'inventaire](https://trello.com/c/L8f3pA4F/23-gestion-de-linventaire)