:bug: Add minimum speed to protect
AlohaGames/RushTheMusic pull request #28
Opened 2021-11-10 20:00 UTC by youenPlusquellec

2021-11-10 22:42 UTC, youenPlusquellec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ajouter une vitesse minimum pour le bouclier](https://trello.com/c/koMdM6Rw/61-ajouter-une-vitesse-minimum-pour-le-bouclier)

2021-11-11 10:15 UTC, DoBrcd requested changes

2021-11-11 10:15 UTC, DoBrcd commented on Assets/Modules/LeapMotion/Scripts/Shield.cs
> +            Debug.Log(speed);
```suggestion
```
Pas de Debug.Log peu utile

2021-11-11 12:35 UTC, DoBrcd approved these changes

2021-11-11 12:35 UTC, merged

2021-11-11 12:37 UTC, Enoriz requested changes

2021-11-11 12:37 UTC, Enoriz commented on Assets/Modules/LeapMotion/Scripts/Shield.cs
> +        [SerializeField] float minimumSpeedToProtect = 0.1f;
Mauvais ordre des variable + mauvaise écriture:
https://docs.google.com/document/d/1c03OGmNt71ovqQKyHZwOr3CFyqgdVP1LEWW5IY5ypEg/edit#