✨ 5 profils
AlohaGames/RushTheMusic pull request #36
Opened 2021-11-12 11:25 UTC by Ailurus13

2021-11-12 20:28 UTC, wilfried7 requested changes

2021-11-12 20:28 UTC, wilfried7 commented on Assets/Modules/Profil/Scripts/ChooseProfilMenu.cs
> +            Debug.Log(profils);
debug.log inutile ?

2021-11-12 20:28 UTC, wilfried7 commented on Assets/Modules/Profil/Scripts/ChooseProfilMenu.cs
> +            // TODO: Ajouter l'UI du profil dans verticalLayout
todo ?

2021-11-12 20:28 UTC, wilfried7 commented on Assets/Modules/Profil/Scripts/Profil.cs
> +        public string name;
public donc name avec majuscule

2021-11-12 20:28 UTC, wilfried7 commented on Assets/Modules/Profil/Scripts/ProfilManager.cs
> +            Debug.Log($"Profil {profil.name} loaded");
debug.log inutile ?

2021-11-12 20:28 UTC, wilfried7 commented on Assets/Modules/Profil/Scripts/ProfilManager.cs
> +            Debug.Log($"Loading files from {getProfilDir()}");
idem

2021-11-15 14:53 UTC, DoBrcd commented
![](https://github.trello.services/images/mini-trello-icon.png) [Profil](https://trello.com/c/22U1A3tC/5-profil)

2021-12-29 14:36 UTC, youenPlusquellec commented on Assets/Modules/Profil/Scripts/ChooseProfilMenu.cs
> +namespace Aloha
Toute la doc

2021-12-29 14:36 UTC, youenPlusquellec commented on Assets/Modules/Profil/Scripts/ChooseProfilMenu.cs
> +        [SerializeField]
Saut de ligne 
```suggestion

        [SerializeField]
```

2021-12-29 14:36 UTC, youenPlusquellec commented on Assets/Modules/Profil/Scripts/NoProfilPickerUI.cs
> +public class NoProfilPickerUI : MonoBehaviour
Toute la doc

2021-12-29 14:36 UTC, youenPlusquellec commented on Assets/Modules/Profil/Scripts/Profil.cs
> +namespace Aloha
Toute la doc

2021-12-29 14:36 UTC, youenPlusquellec commented on Assets/Modules/Profil/Scripts/ProfilManager.cs
> +    public class ProfilManager : Singleton<ProfilManager>
Toute la doc

2022-01-06 08:56 UTC, closed without merging