:construct: end of inventory, check for linter
AlohaGames/RushTheMusic pull request #37
Opened 2021-11-12 20:26 UTC by wilfried7

2021-11-13 16:13 UTC, youenPlusquellec commented on Assets/Modules/Inventory/Scripts/Inventory.cs
> +        public int getMaxItems()
GetMaxItem *

2021-11-13 16:13 UTC, youenPlusquellec commented on Assets/Modules/Inventory/Scripts/UIInventory.cs
> +        void Update()
Pas nécessaire

2021-11-13 16:13 UTC, youenPlusquellec commented on Assets/Modules/Inventory/Scripts/UIInventory.cs
> +                    Debug.Log(horizontalLayoutTransform.sizeDelta.y);*/
Plus besoin des commentaires

2021-11-15 11:31 UTC, DoBrcd requested changes

2021-11-15 11:31 UTC, DoBrcd commented on Assets/Modules/Inventory/Scripts/Inventory.cs
> +        public int getMaxItems()
J'aprouve

2021-11-15 11:31 UTC, DoBrcd commented on Assets/Modules/Inventory/Scripts/UIInventory.cs
> +        void Update()
À supprimer

2021-11-15 15:35 UTC, Enoriz requested changes

2021-11-15 15:35 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/Inventory.cs
>          /// TODO
ça serait bien de faire la doc en même temps

2021-11-15 15:35 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/UIInventory.cs
> +
```suggestion
/// <summary>
/// TODO
/// </summary>
```

2021-11-15 15:35 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/UIInventory.cs
> +
les commentaires je vais pas les faire, il faut faire la doc en même temps que le code

2021-11-15 15:35 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/UIInventory.cs
> +         */
Non conforme

2021-11-15 15:35 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/UIInventory.cs
> +         * */
Non conforme

2021-11-15 15:35 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/UIInventory.cs
> +        // Start is called before the first frame update
Non conforme

2021-11-15 15:35 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/UIInventory.cs
> +
ligne en trop

2021-11-15 15:35 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/UIInventory.cs
> +        // Update is called once per frame
Non conforme

2021-11-15 15:35 UTC, Enoriz commented on Assets/Modules/UI/Scripts/UIManager.cs
ligne en trop

2021-11-15 15:35 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +        // `yield return null;` to skip a frame.
à remlacer par des commentaires conformes

2021-11-15 15:35 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +
ajouter commentaire

2021-11-15 15:35 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +    public class InventoryUITest
ajouter commentaire

2021-11-15 15:35 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +        public IEnumerator InventoryUIWithEnumeratorPasses()
Nom de la fonction n'indique pas ce que fais le test

2021-11-15 15:35 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +        public IEnumerator InventoryUIWithEnumeratorPasses()
Si besoin faire plusieurs fonction avec 
_InventoryUIHorizontalBar_
_InventoryUIVerticalBar_
etc...

2021-11-15 15:35 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +            //check if i have three items now
on utilise pas "je" c'est un commentaire sur l'étape du test
exemple:
_Check if inventory have 3 items_

2021-11-15 15:35 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +            // Adding three item
attention aux fautes "_items_"

2021-11-15 15:35 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +            // start the inventoryUI Starting code (regenrate the Ui)
????

2021-11-15 15:35 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +            // I have 5 max item so i must have 4 child for my horizontalLayoutGroup, the fifth is the firstItem gameobject)
not "I"

2021-11-15 15:35 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +            // There is 3 item so only the three cases must be blue
plus simple

2021-11-15 15:35 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +            // Using an item (heal potion)
juste "Using health potion item"

2021-11-15 15:35 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +            // Now i have only two item
not "I"

2021-11-15 15:35 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +            // I refresh the UI
not "I"

2021-11-15 15:35 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +            // Now the third case must not be blue because i have only two object left
plus simple

2021-11-15 15:35 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +            // adding two more item
Add 2 items

2021-11-15 15:35 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +            inventoryUI.StartCoroutine("ShowCurrentInventoryUI");
kéçéçé?

2021-11-15 15:35 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +            // Now i have four object
not "I"

2021-11-15 15:35 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +            inventoryUI.StartCoroutine("ShowCurrentInventoryUI");
kéçéçé?

2021-11-15 15:35 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +            // Check if only my first four cases are blue
not "I"

2021-11-15 15:35 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +            GameObject.Destroy(horizontalLayoutGroupObject);
Juste utiliser _ClearScene()_

2021-11-18 16:21 UTC, DoBrcd requested changes

2021-11-18 16:21 UTC, DoBrcd commented on Assets/Modules/Inventory/Scripts/HealPotion.cs
> +        /// The class with a the number of life that will be regenerate
```suggestion
        /// The constructor with a the number of life that will be regenerate
```

2021-11-18 16:21 UTC, DoBrcd commented on Assets/Modules/Inventory/Scripts/Inventory.cs
> -        /// </code>
Pourquoi les avoir supprimer ? c'est bien de mettre un exemple

2021-11-18 16:21 UTC, DoBrcd commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +    public class InventoryUITest
@wilfried7 à voir après le merge du pull #39

2021-11-18 16:21 UTC, DoBrcd commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +            // Now the third case must not be blue because i have only two object left
@wilfried7  commentaire pouvant être simplifié

2021-11-19 09:56 UTC, Enoriz requested changes

2021-11-19 09:56 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/HealPotion.cs
> +    /// The item for heal the Hero
This class manage healing potion

2021-11-19 09:56 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/Inventory.cs
> +    /// The singleton which represent the inventory
This class manage the inventory

2021-11-19 09:56 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/HealPotion.cs
> +        /// The class with a the number of life that will be regenerate
il manque un exemple

2021-11-19 09:56 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/HealPotion.cs
> -        /// </example>
il manque un exemple

2021-11-19 09:56 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/Inventory.cs
> -        /// </example>
Exemple

2021-11-19 09:56 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/Inventory.cs
> -        /// </example>
Exemple à ajouter

2021-11-19 09:56 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/Inventory.cs
> +        /// </summary>
Exemple à ajouter

2021-11-19 09:56 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/Item.cs
> +    /// It's an abstract class which represent all the items
This class manage the items

2021-11-19 09:56 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/Item.cs
> -        /// </example>
Exemple à ajouter

2021-11-19 09:56 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/UIInventory.cs
> +        /// </summary>
Exemple à ajouter

2021-11-19 09:56 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/UIInventory.cs
> +        void ShowCurrentInventoryUI()
pouquoi elle est private, elle va pas être appelé par l'UI manager?

2021-11-19 09:56 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/UIInventory.cs
> +
ligne en trop

2021-11-19 09:56 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/UIInventory.cs
> +            Color color = Color.white;
la couleur est pas gérer dans unity directement?

2021-11-19 09:56 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/UIInventory.cs
> +
ligne en trop

2021-11-19 09:56 UTC, Enoriz commented on Assets/Modules/UI/Scripts/UIManager.cs
> -        /// </example>
Exemple à ajouter

2021-11-19 09:56 UTC, Enoriz commented on Assets/Modules/UI/Scripts/UIManager.cs
> +            Inventory.Instance.AddItem(new HealPotion(20));
pourquoi c'est là?

2021-11-19 09:56 UTC, Enoriz commented on Assets/Modules/UI/Scripts/UIManager.cs
> -        /// </example>
Exemple à ajouter

2021-11-19 09:56 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +
up?

2021-11-19 09:56 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +        // `yield return null;` to skip a frame.
up?

2021-11-19 09:56 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +        public IEnumerator InventoryUIWithEnumeratorPasses()
up?

2021-11-19 09:56 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +            // Adding three item
up?

2021-11-19 09:56 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +            //check if i have three items now
up?

2021-11-19 09:56 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +            // start the inventoryUI Starting code (regenrate the Ui)
up?

2021-11-19 09:56 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +            // I have 5 max item so i must have 4 child for my horizontalLayoutGroup, the fifth is the firstItem gameobject)
up?

2021-11-19 18:28 UTC, Enoriz requested changes

2021-11-19 18:28 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/HealPotion.cs
> +        /// HealPotion healpotion = new HealPotion(20);
alinea à ajouter

2021-11-19 18:28 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/HealPotion.cs
> +        /// <example>
<example> Example(s):

2021-11-19 18:28 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/HealPotion.cs
> +        /// <example>
<example> Example(s):

2021-11-19 18:28 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/HealPotion.cs
> +        /// healpotion.Effect();
Alinea à ajouter

2021-11-19 18:28 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/Inventory.cs
> -        /// </code>
up

2021-11-19 18:28 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/Inventory.cs
> -        /// </example>
up

2021-11-19 18:28 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/Inventory.cs
> -        /// </example>
up

2021-11-19 18:28 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/Inventory.cs
> +        /// </summary>
up

2021-11-19 18:28 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/UIInventory.cs
> +    /// It's the class which manage the inventory canvas
This class manage the inventory canvas

2021-11-19 18:28 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/UIInventory.cs
> +            // First, I contruct the UI
pas de "je"

2021-11-19 18:28 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/UIInventory.cs
> +            // Then, i refresh it with the current Items;
pas de "je

2021-11-19 18:28 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/UIInventory.cs
> +        /// </summary>
up

2021-11-19 18:28 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/UIInventory.cs
> +            Color color = Color.white;
up

2021-11-19 18:28 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/UIInventory.cs
> +
up

2021-11-19 18:28 UTC, Enoriz commented on Assets/Modules/UI/Scripts/UIManager.cs
> -        /// </example>
up

2021-11-19 18:28 UTC, Enoriz commented on Assets/Modules/UI/Scripts/UIManager.cs
> +            Inventory.Instance.AddItem(new HealPotion(20));
up

2021-11-19 18:28 UTC, Enoriz commented on Assets/Modules/UI/Scripts/UIManager.cs
> -        /// </example>
up

2021-11-19 18:28 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +        // `yield return null;` to skip a frame.
up

2021-11-19 18:28 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +        public IEnumerator InventoryUIWithEnumeratorPasses()
up

2021-11-19 18:28 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +            // Adding three item
up

2021-11-19 18:28 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +            //check if we have three items now
pas de "we"

2021-11-19 18:28 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +            //check if we have three items now
"Check the number of item in queue"

2021-11-19 18:28 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +            // We have 5 max item so i must have 4 child for my horizontalLayoutGroup, the fifth is the firstItem gameobject)
pas de "we" (voir commentaire précédent)

2021-11-19 18:28 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +            // Inventory have 3 items so we must have 3 blue cases.
pas de "we" (voir commentaire précédent)

2021-11-19 18:28 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +            // Now we have only two item
pas de "we" (voir commentaire précédent)

2021-11-19 18:28 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +            // Now we start the function ShowCurrentInventoryTU
pas de "we" (voir commentaire précédent)

2021-11-19 18:28 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryUITest.cs
> +            // Now we have four object
pas de "we" (voir commentaire précédent)

2021-11-22 19:53 UTC, Enoriz submitted a review, later dismissed

2021-11-23 17:45 UTC, Enoriz requested changes

2021-11-23 17:45 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/UIInventory.cs
> +
up

2021-11-23 17:45 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/UIInventory.cs
> +            // First, contruct the UI
c'est pas le premier truc que tu fais pourtant?

2021-11-23 17:52 UTC, DoBrcd requested changes

2021-11-23 17:52 UTC, DoBrcd commented on Assets/Modules/Inventory/Scripts/Inventory.cs
> +    public class Inventory  : Singleton<Inventory>
```suggestion
    public class InventoryManager  : Singleton<Inventory>
```

2021-11-23 17:52 UTC, DoBrcd commented on Assets/Modules/Inventory/Scripts/Inventory.cs
> +        /// We use the firt item of the queue and we delete it after
```suggestion
        /// Use the first item of the queue and delete it after
```

2021-11-23 17:52 UTC, DoBrcd commented on Assets/Modules/Inventory/Scripts/Inventory.cs
> +        ///     Queue(item) items = inventory.GetItems();
```suggestion
        ///     Queue<Item> items = inventory.GetItems();
```

2021-11-23 17:52 UTC, DoBrcd commented on Assets/Modules/Inventory/Scripts/ItemContainer.cs
> +                //itemDisplayComponent.sprite = linkedItem.sprite
Pourquoi c'est pas fait ?

2021-11-23 17:52 UTC, DoBrcd commented on Assets/Modules/Inventory/Scripts/UIInventory.cs
> +            Debug.Log("maxitem : "+nbMaxItems);
```suggestion
            Debug.Log("maxitem : " + nbMaxItems);
```

2021-11-23 17:52 UTC, DoBrcd commented on Assets/Modules/Inventory/Scripts/UIInventory.cs
> +            Debug.Log("length : " + itemsArray.Length);
Retirer les debugs inutile

2021-11-23 17:52 UTC, DoBrcd commented on Assets/Modules/UI/Scripts/UIManager.cs
> +
Espace ?

2021-11-23 18:32 UTC, youenPlusquellec commented on Assets/Modules/Inventory/Scripts/Inventory.cs
> +        ///     Queue(item) items = inventory.GetItems();
On ne peut pas mettre de <> sinon c'est considéré comme une balise. On met ça à la place

2021-11-23 18:34 UTC, youenPlusquellec commented on Assets/Modules/Inventory/Scripts/ItemContainer.cs
> +                //itemDisplayComponent.sprite = linkedItem.sprite
Parce que ça arrive avec la branche d'eno

2021-11-23 19:08 UTC, youenPlusquellec commented
![](https://github.trello.services/images/mini-trello-icon.png) [UI de l'inventaire](https://trello.com/c/PdEgD3Ub/59-ui-de-linventaire)

2021-11-23 19:35 UTC, Enoriz approved these changes

2021-11-23 20:02 UTC, merged