✨ WIP Add keyboard and mouse support
AlohaGames/RushTheMusic pull request #43
Opened 2021-11-19 17:07 UTC by youenPlusquellec

2021-11-19 18:51 UTC, Enoriz requested changes

2021-11-19 18:51 UTC, Enoriz commented on Assets/Modules/0_Global/Scripts/GameManager.cs
> +        /// bool
A boolean blablabla

2021-11-19 18:51 UTC, Enoriz commented on Assets/Modules/0_Global/Scripts/GameManager.cs
> +        /// Will return if the game is plaing or stopped
plaing ? pl1g?

2021-11-19 18:51 UTC, Enoriz commented on Assets/Modules/0_Global/Scripts/GameManager.cs
> +        /// bool
A boolean blablabla

2021-11-19 18:51 UTC, Enoriz commented on Assets/Modules/Hero/Scripts/ControlManager.cs
> +        // Update is called once per frame
commentaire non conforme :
```suggestion
/// <summary>
/// Update is called once per frame
/// </summary>
```

2021-11-19 18:51 UTC, Enoriz commented on Assets/Modules/Hero/Scripts/ControlManager.cs
> +        private void MoveHandsWithMouse()
_private_ pas nécessaire

2021-11-19 18:51 UTC, Enoriz commented on Assets/Modules/Hero/Scripts/ControlSelector.cs
> +        [SerializeField]
ligne avant

2021-11-19 18:51 UTC, Enoriz commented on Assets/Modules/Hero/Scripts/ControlSelector.cs
> +        // Update is called once per frame
```suggestion
/// <summary>
/// Update is called once per frame
/// </summary>
```

2021-11-19 18:51 UTC, Enoriz commented on Assets/Modules/Hero/Scripts/WarriorControlManager.cs
> +        void Start()
```suggestion
/// <summary>
/// Is called on the frame when a script is enabled just before any of the Update methods are called the first time.
/// </summary>
void Start()
```

2021-11-19 18:51 UTC, Enoriz commented on Assets/Modules/Hero/Scripts/WarriorControlManager.cs
> +            rightHandAnimator.SetTrigger("Attack");
tu fais pas de base.PrepareAttack()  même si ta fonction dont tu hérite est vide?

2021-11-19 18:51 UTC, Enoriz commented on Assets/Modules/Hero/Scripts/WarriorControlManager.cs
> +        }
```suggestion
        protected override void ReleaseAttack() { }
```

2021-11-19 18:51 UTC, Enoriz commented on Assets/Modules/Hero/Scripts/WarriorControlManager.cs
> +        }
je suis pas sur de moi pour les espaces, à vérifier avec @DoBrcd

2021-11-19 18:51 UTC, Enoriz commented on Assets/Modules/Hero/Scripts/WarriorControlManager.cs
> +            leftHandAnimator.SetBool("isDefending", true);
tu fais pas de base.PrepareAttack() même si ta fonction dont tu hérite est vide?

2021-11-19 18:51 UTC, Enoriz commented on Assets/Modules/Hero/Scripts/WarriorControlManager.cs
> +            leftHandAnimator.SetBool("isDefending", false);
tu fais pas de base.PrepareAttack() même si ta fonction dont tu hérite est vide?

2021-11-19 18:51 UTC, Enoriz commented on Assets/Modules/Hero/Scripts/WizardControlManager.cs
> +        private void Awake()
private pas nécessaire

2021-11-19 18:51 UTC, Enoriz commented on Assets/Modules/Hero/Scripts/WizardControlManager.cs
> +}
ligne à ajouter

2021-11-19 18:51 UTC, Enoriz commented on Assets/Modules/LeapMotion/Scripts/FireballSpawner.cs
> +        private Material raycastMaterial;
ligne à ajouter en dessous

2021-11-19 18:51 UTC, Enoriz commented on Assets/Modules/LeapMotion/Scripts/FireballSpawner.cs
> +        // Update is called once per frame
commentaire non conforme, ajouter <summary></summary>

2021-11-19 18:51 UTC, Enoriz commented on Assets/Modules/LeapMotion/Scripts/FireballSpawner.cs
> +}
ligne à ajouter

2021-11-22 12:22 UTC, youenPlusquellec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Support du clavier souris](https://trello.com/c/GMFQK7Y8/67-support-du-clavier-souris)

2021-11-22 12:22 UTC, youenPlusquellec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Support du clavier souris](https://trello.com/c/GMFQK7Y8/67-support-du-clavier-souris)

2021-11-22 12:28 UTC, Enoriz commented on Assets/Modules/LeapMotion/Scripts/FireballSpawner.cs
> +        private Vector3? endPoint;
Vector3? pourquoi un ? il peut être null?

2021-11-22 12:30 UTC, Enoriz submitted a review, later dismissed

2021-11-22 14:25 UTC, youenPlusquellec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Utilisation d'un item](https://trello.com/c/xWSuOyn6/24-utilisation-dun-item)

2021-11-22 14:55 UTC, Ailurus13 approved these changes

2021-11-22 14:56 UTC, merged