:tada: Now Enemy are intelligente
AlohaGames/RushTheMusic pull request #47
Opened 2021-11-23 17:39 UTC by DoBrcd

2021-11-23 17:51 UTC, youenPlusquellec commented on Assets/Modules/0_Global/Scripts/Utils.cs
>          /// TODO
Add doc

2021-11-23 17:51 UTC, youenPlusquellec commented on Assets/Modules/0_Global/Scripts/Utils.cs
> +        public static bool IsEmpty<T>(this List<T> list)
Il manque la doc

2021-11-23 17:51 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/Graph.cs
> +        public int EntryNode = 0;
Saut de ligne pas nécessaires entre les variables ?

2021-11-23 17:51 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/Graph.cs
> +        public void SetCurrentNode(Node node)
Les fuckings commentaires dans TOUT LE FICHIER

2021-11-23 17:51 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/GraphRunner.cs
> +        private void Start()
LES COMMENTAIRES PARTOUT

2021-11-23 17:51 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/GraphRunner.cs
> +        public IEnumerator currentCoroutine = null;
CurrentCoroutine *

2021-11-23 17:51 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/LancerGraph.cs
> +namespace Aloha.AI
La doc

2021-11-23 17:51 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/LancerGraph.cs
> +        public override void Start()
Tu peux mettre des commentaires sur chaque bloc de code

2021-11-23 17:51 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/Link.cs
> +        public Node from;
From*
To*

2021-11-23 17:51 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/Link.cs
> +        public float probability = 1.0f;
Probability*

2021-11-23 17:51 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/Link.cs
> +        public UnityEvent triggerEvent = null;
TriggerEvent

2021-11-23 17:51 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/Link.cs
> +        public EventLink(UnityEvent triggerEvent)
La doc partout

2021-11-23 17:51 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/Node.cs
> +{
La doc partout

2021-11-23 17:51 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/Nodes/BasicNode.cs
> +namespace Aloha.AI
La doc

2021-11-23 17:51 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/Nodes/GoToHero.cs
> +        public float proximity = 5.0f;
Majuscule

2021-11-23 17:51 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/Nodes/LancerAttack.cs
> +        public float distToMove = 0.5f;
Majuscule partout sur les publics

2021-11-23 17:51 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/Nodes/Move.cs
> +        public float distToMove = 0.5f;
Majuscule partout sur les publics

2021-11-23 18:03 UTC, Enoriz requested changes

2021-11-23 18:03 UTC, Enoriz commented on Assets/Modules/Enemy/Scripts/Enemy.cs
> +                    //GetComponent<GraphRunner>()?.StartGraph();
pourquoi en commentaire?

2021-11-23 18:03 UTC, Enoriz commented on Assets/Modules/Enemy/Scripts/Lancer.cs
> +                        temps += speed * Time.deltaTime;
temps?

2021-11-23 18:03 UTC, Enoriz commented on Assets/Modules/Enemy/Scripts/Wall.cs
> +            // if (isTilesStopped) runAndStopTiles();
why?

2021-11-23 18:03 UTC, Enoriz commented on Assets/Modules/Tiles/Scripts/TilesManager.cs
> +        [SerializeField]
il s'est perdu lui?

2021-11-24 08:34 UTC, DoBrcd commented on Assets/Modules/0_Global/Scripts/Utils.cs
>          /// TODO
Je crois je l'ai fait dans une autre branche

2021-11-30 09:09 UTC, Enoriz requested changes

2021-11-30 09:09 UTC, Enoriz commented on Assets/Modules/AI/Scripts/Graph.cs
> +    public class Graph : ScriptableObject
up

2021-11-30 09:09 UTC, Enoriz commented on Assets/Modules/AI/Scripts/Graph.cs
> +
up

2021-11-30 09:09 UTC, Enoriz commented on Assets/Modules/AI/Scripts/Graph.cs
> +        public int EntryNode = 0;
nop

2021-11-30 09:09 UTC, Enoriz commented on Assets/Modules/AI/Scripts/Graph.cs
> +        public void SetCurrentNode(Node node)
up (le dernier se trouve au niveau de la classe)

2021-11-30 09:09 UTC, Enoriz commented on Assets/Modules/AI/Scripts/Graph/WallGraph.cs
> +
ligne en trop

2021-11-30 09:09 UTC, Enoriz commented on Assets/Modules/AI/Scripts/Nodes/AssassinConcentration.cs
> +            Debug.Log(posFinal);
Remove or not remove?

2021-11-30 09:09 UTC, Enoriz commented on Assets/Modules/AI/Scripts/Nodes/LancerAttack.cs
> +        public float distToMove = 0.5f;
up

2021-11-30 09:09 UTC, Enoriz commented on Assets/Modules/AI/Scripts/Nodes/WyrmlingAttack.cs
> +
ligne en trop

2021-11-30 09:09 UTC, Enoriz commented on Assets/Modules/AI/Scripts/Nodes/WyrmlingAttack.cs
> +        public float distToMove = 0.5f;
Maj sur les var public

2021-11-30 09:09 UTC, Enoriz commented on Assets/Modules/Enemy/Scripts/Assassin.cs
> +        public Animator anim;
Maj sur var pub

2021-11-30 09:09 UTC, Enoriz commented on Assets/Modules/Enemy/Scripts/Assassin.cs
> +                */
Pourquoi c'est en commentaire?

2021-11-30 09:09 UTC, Enoriz commented on Assets/Modules/Enemy/Scripts/Enemy.cs
>          private EnemyStats enemyStats
mauvais ordre de var

2021-11-30 09:09 UTC, Enoriz commented on Assets/Tests/PlayMode/Inventory/InventoryTest.cs
> +        /*[Test]
?

2021-11-30 09:32 UTC, youenPlusquellec commented on Assets/Modules/0_Global/Scripts/GameManager.cs
>      {
public après les private

2021-11-30 09:32 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/Graph.cs
> +    public class Graph : ScriptableObject
Up

2021-11-30 09:32 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/Graph.cs
> +
Up

2021-11-30 09:32 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/GraphRunner.cs
> +        [SerializeField]
Saut de ligne avant le SerializeField

2021-11-30 09:32 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/Nodes/AssassinAttack.cs
> +        public float distToMove = 0.5f;
Des majuscules sur les publics

2021-11-30 09:32 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/Nodes/AssassinConcentration.cs
> +            Debug.Log(posFinal);
Maybe maybe not ?

2021-11-30 09:32 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/Nodes/AssassinConcentration.cs
> +            Debug.Log(posFinal);
Pitetre bin que oui, pitietre bin que non

2021-11-30 09:32 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/Nodes/WyrmlingAttack.cs
> +        public float actionTime = 1f;
Maj

2021-11-30 09:32 UTC, youenPlusquellec commented on Assets/Modules/Entity/Script/Entity.cs
> +                Debug.Log("Active again wasTriggered");
On garde le debug ?

2021-11-30 09:32 UTC, youenPlusquellec commented on Assets/Modules/Tiles/Scripts/TilesManager.cs
> +        [SerializeField]
Up Wtf ?

2021-11-30 10:13 UTC, DoBrcd commented on Assets/Modules/0_Global/Scripts/GameManager.cs
>      {
Nop

2021-11-30 13:56 UTC, Enoriz requested changes

2021-11-30 13:56 UTC, Enoriz commented on Assets/Modules/AI/Scripts/Graph/WallGraph.cs
> +
ligne en trop (up)

2021-11-30 13:56 UTC, Enoriz commented on Assets/Modules/AI/Scripts/GraphRunner.cs
> +        private void StopNodeAction()
les private sont pas sous-entendu?

2021-11-30 13:56 UTC, Enoriz commented on Assets/Modules/AI/Scripts/Nodes/AssassinConcentration.cs
> +        public float distToMove = 0.5f;
variables publiques en majuscule

2021-11-30 13:56 UTC, Enoriz commented on Assets/Modules/AI/Scripts/Nodes/WyrmlingAttack.cs
> +        public WyrmlingAttack(Graph graph) : base(graph)
c'est quoi le _: base(graph)_ ?

2021-11-30 13:56 UTC, Enoriz commented on Assets/Modules/Enemy/Scripts/Enemy.cs
> +//using Aloha.AI;
Delete or not delete?

2021-11-30 13:56 UTC, Enoriz commented on Assets/Modules/Enemy/Scripts/EnemyInstantier.cs
> +        private GameObject InstantiateEnemy(int id)
private sous entendu non?

2021-11-30 13:56 UTC, Enoriz commented on Assets/Modules/Entity/Script/Entity.cs
> +
ligne en trop

2021-11-30 15:15 UTC, DoBrcd commented on Assets/Modules/0_Global/Scripts/GameManager.cs
> +        public bool IsGameInfinite = false;
Je me demande si il marche pas

2021-11-30 15:25 UTC, DoBrcd commented on Assets/Modules/0_Global/Scripts/GameManager.cs
> +        public bool IsGameInfinite = false;
C'est viré

2021-11-30 15:38 UTC, DoBrcd commented on Assets/Modules/AI/Scripts/Nodes/WyrmlingAttack.cs
> +        public WyrmlingAttack(Graph graph) : base(graph)
Un truc bien

2021-11-30 15:39 UTC, DoBrcd commented on Assets/Modules/Enemy/Scripts/Enemy.cs
> +//using Aloha.AI;
DELETE

2021-11-30 15:42 UTC, DoBrcd commented on Assets/Modules/Entity/Script/Entity.cs
> +
Non c'est pour faire des lignes facilement lisible

2021-11-30 16:00 UTC, Enoriz requested changes

2021-11-30 16:08 UTC, Enoriz submitted a review, later dismissed

2021-12-01 14:00 UTC, youenPlusquellec approved these changes

2021-12-01 14:04 UTC, merged