✨ Add chest prefab
AlohaGames/RushTheMusic pull request #50
Opened 2021-11-24 16:58 UTC by youenPlusquellec

2021-11-28 19:40 UTC, Enoriz requested changes

2021-11-28 19:40 UTC, Enoriz commented on Assets/Modules/Enemy/Scripts/Chest.cs
> +
ligne en trop

2021-11-28 19:40 UTC, Enoriz commented on Assets/Modules/Enemy/Scripts/Chest.cs
> +        ///     warrior.Init();
pourquoi warrior?

2021-11-28 19:40 UTC, Enoriz commented on Assets/Modules/Enemy/Scripts/Chest.cs
> +        /// <param name="direction"></param>
```suggestion
        /// <param name="direction">The direction of enemy bumping</param>
```
c'est bien ça?

2021-11-28 19:40 UTC, Enoriz commented on Assets/Modules/Enemy/Scripts/Chest.cs
> +        /// <param name="speed"></param>
comme précédent, une petite description de la variable

2021-11-28 19:40 UTC, Enoriz commented on Assets/Modules/Enemy/Scripts/Enemy.cs
>          protected bool AIActivated = false;
les variables "protected" avant les "private"
RAPPEL:
private
protected
public

2021-11-28 19:40 UTC, Enoriz commented on Assets/Modules/Enemy/Scripts/Wall.cs
> +        /// <param name="speed"></param>
petite description des paramètres

2021-11-28 19:40 UTC, Enoriz commented on Assets/Modules/Entity/Script/Entity.cs
> +        private IEnumerator SwitchColor()
private est sous entendu

2021-11-28 19:40 UTC, Enoriz commented on Assets/Modules/LeapMotion/Scripts/Fireball.cs
> +            Destroy(gameObject, 2f);
c'est quoi le float en 2e paramètre?

2021-11-28 20:09 UTC, youenPlusquellec commented on Assets/Modules/LeapMotion/Scripts/Fireball.cs
> +            Destroy(gameObject, 2f);
C'est le temps après lequel l'objet va être détruit.

2021-11-30 08:03 UTC, Ailurus13 approved these changes

2021-11-30 08:03 UTC, Ailurus13 commented
Ajout de la potion secondaire dans un autre ticket plus tard

2021-11-30 08:03 UTC, merged