✨ Add canon prefab
AlohaGames/RushTheMusic pull request #67
Opened 2021-12-28 22:53 UTC by youenPlusquellec

2021-12-28 22:53 UTC, youenPlusquellec commented
Waiting for sprites and animations

2021-12-29 14:32 UTC, youenPlusquellec commented on Assets/Modules/Enemy/Scripts/Canon.cs
> +    /// TODO
Add comment

2021-12-29 14:32 UTC, youenPlusquellec commented on Assets/Modules/Enemy/Scripts/Canon.cs
> +            StartCoroutine(WaitForAttackAvailable());
Explain why

2021-12-29 14:32 UTC, youenPlusquellec commented on Assets/Modules/Enemy/Scripts/Canon.cs
> +            // Kill the chest if it goes behing the player
```suggestion
            // Kill the **canon** if it goes behing the player
```

2021-12-29 14:32 UTC, youenPlusquellec commented on Assets/Modules/Enemy/Scripts/Canon.cs
> +        ///     StartCoroutine(wall.GetBump(new Vector3(0, 0, 2), 2));
```suggestion
        ///     StartCoroutine(canon.GetBump(new Vector3(0, 0, 2), 2));
```

2021-12-29 14:32 UTC, youenPlusquellec commented on Assets/Modules/Enemy/Scripts/Canon.cs
> +        /// Bump the entity in a specific direction and with a speed
```suggestion
        /// Bump the entity in a specific direction and with a speed
        /// In this case, the canon never moves
```

2021-12-29 14:32 UTC, youenPlusquellec commented on Assets/Modules/Enemy/Scripts/Canon.cs
> +        /// Instance and launch a fireball
```suggestion
        /// Instance and launch a canonball
```

2021-12-29 14:32 UTC, youenPlusquellec commented on Assets/Modules/Enemy/Scripts/Canon.cs
> +            StartCoroutine(WaitForAttackAvailable());
Explain what it is

2021-12-29 14:32 UTC, youenPlusquellec commented on Assets/Modules/Enemy/Scripts/CanonBall.cs
> +    /// TODO
Doc

2021-12-29 14:32 UTC, youenPlusquellec commented on Assets/Modules/Enemy/Scripts/Enemy.cs
> +            // Usefull for debug scenes
Explain more

2021-12-29 14:32 UTC, youenPlusquellec commented on Assets/Tests/PlayMode/Enemy/WyrmlingTest.cs
> +            Debug.Log("Instantiate");
Remove debug

2022-01-05 08:24 UTC, Enoriz requested changes

2022-01-05 08:24 UTC, Enoriz commented on Assets/Modules/AI/Scripts/Nodes/AssassinAttack.cs
> +            assassin.Attack(assassin.Hero);
y a plus besoin d'instancier le héro?

2022-01-05 08:24 UTC, Enoriz commented on Assets/Modules/AI/Scripts/Nodes/CanonAttack.cs
> +            canon.Fire();
c'est quoi la fonction Fire()?

2022-01-05 08:24 UTC, Enoriz commented on Assets/Modules/AI/Scripts/Nodes/CanonAttack.cs
> +        /// Make the lancer Attack
c'esst un canon pas un lancier

2022-01-05 08:24 UTC, Enoriz commented on Assets/Modules/AI/Scripts/Nodes/LancerAttack.cs
> +            lancer.Attack(lancer.Hero);
même question d'instanciation

2022-01-05 08:24 UTC, Enoriz commented on Assets/Modules/AI/Scripts/Nodes/WyrmlingMove.cs
> +                Vector3 tmpPos = Vector3.Lerp(posInit, posFinal, time / ActionTime);
c'est quoi Lerp()?

2022-01-05 08:24 UTC, Enoriz commented on Assets/Modules/Enemy/Scripts/Assassin.cs
> -            hero = GameManager.Instance.GetHero();
même question d'instanciation

2022-01-05 08:24 UTC, Enoriz commented on Assets/Modules/Enemy/Scripts/Enemy.cs
> +                this.Hero = GameManager.Instance.GetHero();
pourquoi là tu l'instancie?

2022-01-05 08:24 UTC, Enoriz commented on Assets/Tests/PlayMode/Enemy/CanonBallTest.cs
> +}
c bô

2022-01-05 08:24 UTC, Enoriz commented on Assets/Tests/PlayMode/Enemy/WyrmlingTest.cs
> +            wyrmling.Hero = warrior;
dragon.hero?

2022-01-05 09:08 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/Nodes/AssassinAttack.cs
> +            assassin.Attack(assassin.Hero);
Nop, c'était vraiment pas pratique. 
Du coup maintenant, s'il y a un hero dans le gameManager il le récupère, sinon on peut le lui passer par paramètre.

2022-01-05 09:09 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/Nodes/CanonAttack.cs
> +            canon.Fire();
En français la méthode serait "faireFeu()" en gros.

2022-01-05 09:09 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/Nodes/LancerAttack.cs
> +            lancer.Attack(lancer.Hero);
Lié à cette réponse : https://github.com/AlohaGames/RushTheMusic/pull/67#discussion_r778652641
Le héro est maintenant dispo dans les paramètres d'ennemis

2022-01-05 09:10 UTC, youenPlusquellec commented on Assets/Modules/AI/Scripts/Nodes/WyrmlingMove.cs
> +                Vector3 tmpPos = Vector3.Lerp(posInit, posFinal, time / ActionTime);
C'est une méthode d'interpolation linéaire. 
Tu lui donnes un point A et un point B et un pourcentage et il te calcul l'emplacement entre A et B pour un pourcentage donné

2022-01-05 09:12 UTC, youenPlusquellec commented on Assets/Modules/Enemy/Scripts/Assassin.cs
> -            hero = GameManager.Instance.GetHero();
Lié à ça : https://github.com/AlohaGames/RushTheMusic/pull/67#discussion_r778652641
C'est un moyen d'éviter d'avoir à instancier un gameManager et un héro dans chaque scène. On peut le lui passer en paramètre si on le souhaite.

2022-01-05 09:12 UTC, youenPlusquellec commented on Assets/Modules/Enemy/Scripts/Enemy.cs
> +                this.Hero = GameManager.Instance.GetHero();
Toujours pareil : https://github.com/AlohaGames/RushTheMusic/pull/67#discussion_r778652641
La récupération du Hero se fait juste ici

2022-01-05 09:13 UTC, youenPlusquellec commented on Assets/Tests/PlayMode/Enemy/CanonBallTest.cs
> +}
Je sais, je suis trop fort

2022-01-05 09:14 UTC, youenPlusquellec commented on Assets/Tests/PlayMode/Enemy/WyrmlingTest.cs
> +            wyrmling.Hero = warrior;
Maintenant on a plus besoin de lier le hero au manager, on peut le passer en paramètre. 
Toujours lié à ça : https://github.com/AlohaGames/RushTheMusic/pull/67#discussion_r778652641

2022-01-05 09:19 UTC, Enoriz commented on Assets/Tests/PlayMode/Enemy/WyrmlingTest.cs
> +            wyrmling.Hero = warrior;
ça fait un peu bizarre de le voir en paramètre de l'ennemi

2022-01-05 12:58 UTC, youenPlusquellec commented on Assets/Tests/PlayMode/Enemy/WyrmlingTest.cs
> +            wyrmling.Hero = warrior;
Avec le système actuel on est obligé de le faire comme ça maintenant, je viens de m'en souvenir

2022-01-05 22:38 UTC, youenPlusquellec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Prefab Canon](https://trello.com/c/wbMAIN9E/16-prefab-canon)

2022-01-06 08:12 UTC, Enoriz approved these changes

2022-01-06 08:30 UTC, merged