✨ Add experience system
AlohaGames/RushTheMusic pull request #68
Opened 2021-12-29 14:19 UTC by youenPlusquellec

- Experience system
- Experience UI
- Experience bottle
- Dynamic texts

2021-12-29 14:25 UTC, youenPlusquellec commented on Assets/Modules/DynamicText/Scripts/DynamicText.cs
> +namespace Aloha
Il manque toute la doc

2021-12-29 14:25 UTC, youenPlusquellec commented on Assets/Modules/DynamicText/Scripts/DynamicTextManager.cs
> +namespace Aloha
Il manque toute la doc

2021-12-29 14:25 UTC, youenPlusquellec commented on Assets/Modules/Enemy/Scripts/Enemy.cs
> +        public void gainXP(Hero hero)
Ajouter la doc

2021-12-29 14:25 UTC, youenPlusquellec commented on Assets/Modules/Inventory/Scripts/ExperiencePotion.cs
> +        /// Give an effect to the mana potion. It regenerate the mana.
```suggestion
        /// Give an effect to the **experience** potion. It **gives a level of xp**.
```

2021-12-29 14:25 UTC, youenPlusquellec commented on Assets/Modules/Inventory/Scripts/ExperiencePotion.cs
> +        ///     manaPotion.Effect();
```suggestion
        ///     experiencePotion.Effect();
```

2021-12-29 14:25 UTC, youenPlusquellec commented on Assets/Modules/UI/Scripts/Bar/ExpBar.cs
> +            Debug.Log("J'update l'XP tmtc");
Remove debugs

2022-01-06 08:09 UTC, Enoriz requested changes

2022-01-06 08:09 UTC, Enoriz commented on Assets/Modules/DynamicText/Scripts/DynamicText.cs
> +
ligne en trop

2022-01-06 08:09 UTC, Enoriz commented on Assets/Modules/DynamicText/Scripts/DynamicTextManager.cs
> +
ligne en trop x3

2022-01-06 08:09 UTC, Enoriz commented on Assets/Modules/Enemy/Scripts/Enemy.cs
> +            hero.LevelUp(xpGain);
la fonctino levelUp donne de l'xP, c'est pas plutôt quand tu gagnes un niveau?

2022-01-06 08:09 UTC, Enoriz commented on Assets/Modules/Entity/Script/Entity.cs
> +            this.stats = Instantiate(stats);
on instantie les stats?

2022-01-06 08:09 UTC, Enoriz commented on Assets/Modules/Hero/Scripts/Hero.cs
> +            // LEVEL UP !
ça devrait pas être dans la fonciton LevelUp()?

2022-01-06 08:09 UTC, Enoriz commented on Assets/Modules/Inventory/Scripts/ExperiencePotion.cs
> +}
manque une ligne à la fin

2022-01-06 08:09 UTC, Enoriz commented on Assets/Modules/Mapping/Scripts/EnemySpawner.cs
> +        private int heroLevel = -1;
variable private avant les public

2022-01-06 08:09 UTC, Enoriz commented on Assets/Modules/Mapping/Scripts/EnemySpawner.cs
> +                    // TODO-TRISTAN: Scale stats based on this.heroLevel
normal?

2022-01-06 08:09 UTC, Enoriz commented on Assets/Modules/UI/Scripts/Bar/ExpBar.cs
> +        /// TODO
doc à finir

2022-01-06 13:41 UTC, Ailurus13 commented on Assets/Modules/Entity/Script/Entity.cs
> +            this.stats = Instantiate(stats);
oui

2022-01-06 13:43 UTC, Ailurus13 commented on Assets/Modules/UI/Scripts/Bar/ExpBar.cs
> +        /// TODO
j'ignore car branche de doc

2022-01-06 15:47 UTC, Enoriz approved these changes

2022-01-06 16:03 UTC, merged