🐛 Warrior hands bug
AlohaGames/RushTheMusic pull request #73
Opened 2022-01-07 19:49 UTC by youenPlusquellec

2022-01-07 19:49 UTC, youenPlusquellec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Bras du guerrier](https://trello.com/c/KIHoYA68/117-bras-du-guerrier)

2022-01-07 22:21 UTC, Enoriz requested changes
Une photo dans la PR serait cool pour voir les changements

2022-01-07 22:21 UTC, Enoriz commented on Assets/Modules/LeapMotion/Scripts/Sword.cs
> +                if (!leapActivated) Speed = 2;
pourquoi la speed augmente quand c'est la leap?

2022-01-07 22:35 UTC, youenPlusquellec commented on Assets/Modules/LeapMotion/Scripts/Sword.cs
> +                if (!leapActivated) Speed = 2;
Au contraire, on fixe une vitesse si on utilise pas la leap. Pour éviter que les ennemis soient envoyés à 3km

2022-01-07 22:37 UTC, youenPlusquellec commented
![image](https://user-images.githubusercontent.com/33334707/148616243-16825ddd-7b50-4c6c-bab2-b1f4705b220f.png)

2022-01-07 22:38 UTC, youenPlusquellec commented
![image](https://user-images.githubusercontent.com/33334707/148616300-e10d2b54-4261-4f2d-960d-c5a2bf4a3f7d.png)

2022-01-10 07:31 UTC, Enoriz approved these changes

2022-01-10 08:07 UTC, merged