✨ Add new HUD effects
AlohaGames/RushTheMusic pull request #77
Opened 2022-01-08 02:51 UTC by youenPlusquellec

2022-01-08 02:52 UTC, youenPlusquellec commented
Effet visuels de dégats : 
![damages](https://user-images.githubusercontent.com/33334707/148628981-e71ea380-b83a-4a6d-84be-4c8454c1c6b6.png)

Effet visuels de heal : 
![heal](https://user-images.githubusercontent.com/33334707/148628984-5b45fe58-0992-453d-a853-9aa6dfb32779.png)

2022-01-08 02:54 UTC, youenPlusquellec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ajouter un effet visuel de prise de dégats pour le héros](https://trello.com/c/YDrmVWHw/89-ajouter-un-effet-visuel-de-prise-de-d%C3%A9gats-pour-le-h%C3%A9ros)

2022-01-09 13:45 UTC, Enoriz requested changes
j'adore le HUD de prise de dégâts mais pas du tout celui de heal, un petit +xxlp an vert aurait suffit (à la manière des dégâts subit par les ennemis)

2022-01-09 15:31 UTC, youenPlusquellec commented
> j'adore le HUD de prise de dégâts mais pas du tout celui de heal, un petit +xxlp an vert aurait suffit (à la manière des dégâts subit par les ennemis) Ou alors mettre des "+" vert tout autour du héro, à discuter

Yep je suis d'accord, à discuter tous ensemble

2022-01-10 07:43 UTC, Ailurus13 commented
> 

Moi pour le coup j'aime ni l'un ni l'autre.
Ils prennent trop de place et pollue l'espace à mon avis. Ils sont pas vraiment dans le style des autres assets. Mais j'adore l'idée d'ajouter un petit quelque chose sur l'écran pour montrer les dégats / heal

2022-01-10 08:38 UTC, DoBrcd commented
> Moi pour le coup j'aime ni l'un ni l'autre. Ils prennent trop de place et pollue l'espace à mon avis. Ils sont pas vraiment dans le style des autres assets. Mais j'adore l'idée d'ajouter un petit quelque chose sur l'écran pour montrer les dégats / heal

Je pense que on peu tfaire un truc plus simple moins violent : 
 - Un simple clignotement léger rouge à la manière des ennemies quand on prend des dégats
 - J'aime bien l'idée d'avoir des petits croix vertes dans le champ de visions

2022-01-10 12:22 UTC, youenPlusquellec commented
Nouvel effet visuel de dégats : 
![image](https://user-images.githubusercontent.com/33334707/148765249-dcd6c8f3-e7b8-46cc-bc79-7490ec8af9c3.png)

Nouvel effet visuel de healing : 
![image](https://user-images.githubusercontent.com/33334707/148765154-f4500ecb-9978-49e2-98f3-9b647b25122d.png)

2022-01-10 12:48 UTC, merged