✨ Add more settings
AlohaGames/RushTheMusic pull request #82
Opened 2022-01-09 05:39 UTC by youenPlusquellec

Tous les paramètres ont été liés au jeu

![image](https://user-images.githubusercontent.com/33334707/148670716-5b126045-f6f9-41f7-ac03-b85bfe8eda66.png)

![image](https://user-images.githubusercontent.com/33334707/148670723-7b789461-10d3-49d8-8596-3a13e25e3d62.png)

2022-01-09 05:43 UTC, youenPlusquellec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ajout de plus d'options](https://trello.com/c/C3cKs7fj/120-ajout-de-plus-doptions)

2022-01-09 13:37 UTC, Enoriz requested changes

2022-01-09 13:37 UTC, Enoriz commented on Assets/Modules/0_Global/Scripts/GameManager.cs
> +        public float MouseSensibility = 1.0f;
ça devrait pas être dans une classe "Settings"?

2022-01-09 13:37 UTC, Enoriz commented on Assets/Modules/Mapping/Scripts/AudioManager.cs
> +        public void UpdateVolume(float volume)
t'as ajouté un audio dans la scene de base?

2022-01-09 15:25 UTC, youenPlusquellec commented on Assets/Modules/0_Global/Scripts/GameManager.cs
> +        public float MouseSensibility = 1.0f;
Il faut que ce soit dans le manager principal pour que ce soit accessible depuis n'importe où.

2022-01-09 15:26 UTC, youenPlusquellec commented on Assets/Modules/Mapping/Scripts/AudioManager.cs
> +        public void UpdateVolume(float volume)
Y'avait déjà cet audio, c'est celui qui instancie la musique.

2022-01-09 15:37 UTC, youenPlusquellec commented on Assets/Modules/0_Global/Scripts/GameManager.cs
> +        public float MouseSensibility = 1.0f;
Au mieux on aurait pu le mettre dans un nouveau manager, mais ça me parait abusé d'en créer un nouveau jute pour stocker des variables.

2022-01-10 07:28 UTC, Enoriz requested changes

2022-01-10 07:28 UTC, Enoriz commented on Assets/Modules/Mapping/Scripts/AudioManager.cs
> +        public void UpdateVolume(float volume)
d'une scène à une autre le son reste inchangé?

2022-01-10 07:32 UTC, youenPlusquellec commented on Assets/Modules/Mapping/Scripts/AudioManager.cs
> +        public void UpdateVolume(float volume)
Il modifie le son du gameObject qui gère le son, qui visiblement existe dès le début et n'est pas supprimé d'après ce que j'ai vu.

2022-01-10 07:34 UTC, Ailurus13 commented on Assets/Modules/0_Global/Scripts/GameManager.cs
> +        public float MouseSensibility = 1.0f;
Tu peux faire une classe Config et avoir une variable dans le manager 

```
public Config config;
```

2022-01-10 07:35 UTC, Ailurus13 commented on Assets/Modules/Mapping/Scripts/AudioManager.cs
> +        public void UpdateVolume(float volume)
Il n'existe pas dès le début normalement vu qu'il ai généré au moment du chargement de la première map

2022-01-10 07:44 UTC, youenPlusquellec commented on Assets/Modules/Mapping/Scripts/AudioManager.cs
> +        public void UpdateVolume(float volume)
Pourtant le son est bien update quand je modifie le son depuis les paramètres. 
Je vais voir pour stocker ça dans une variable qu'il lira aussi à l'instanciation du coup.

2022-01-10 07:45 UTC, youenPlusquellec commented on Assets/Modules/0_Global/Scripts/GameManager.cs
> +        public float MouseSensibility = 1.0f;
> Tu peux faire une classe Config et avoir une variable dans le manager
> 
> ```cs
> public RtmConfig Config;
> ```

Ah oui pas con, je vais faire ça. C'était la solution que je cherchais à laquelle je n'ai pas pensé

2022-01-10 08:34 UTC, DoBrcd commented on Assets/Modules/Mapping/Scripts/AudioManager.cs
> +        public void UpdateVolume(float volume)
Il faut que le son soit généraliser : 
 - En gros une variable globale de volume
 - Et chaque audio source (celle de la musique + celles des bruitages) viennent chercher cette valeur

2022-01-10 08:35 UTC, youenPlusquellec commented on Assets/Modules/Mapping/Scripts/AudioManager.cs
> +        public void UpdateVolume(float volume)
> Il faut que le son soit généraliser :

Ouai c'est ce que j'étais en train de rajouter du coup

2022-01-10 10:59 UTC, merged

2022-01-14 00:07 UTC, youenPlusquellec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Faire scale les statistiques des héros / ennemies en fonction du niveau.](https://trello.com/c/MvyBuvtV/105-faire-scale-les-statistiques-des-h%C3%A9ros-ennemies-en-fonction-du-niveau)