:sparkles:  82 - Add infinite mode
AlohaGames/RushTheMusic pull request #84
Opened 2022-01-10 15:45 UTC by Ailurus13

# Trello
https://trello.com/c/MpMEtunX/82-mode-infini

# Nouveau bouton menu principal
![image](https://user-images.githubusercontent.com/43964335/148794392-3a7df96d-9817-4859-a99e-ef7d6e312334.png)

# Score total du mode infini
![image](https://user-images.githubusercontent.com/43964335/148794883-4a968952-aa87-4564-ba92-9bfc22a6dc45.png)

2022-01-10 16:38 UTC, youenPlusquellec commented on Assets/Modules/UI/Scripts/Menu/InfiniteModeNextLevelButton.cs
> +        public void onFinishLoad()
doc

2022-01-10 16:38 UTC, youenPlusquellec commented on Assets/Modules/UI/Scripts/Menu/InfiniteModeNextLevelButton.cs
> +        void Awake()
doc

2022-01-10 16:38 UTC, youenPlusquellec commented on Assets/Modules/UI/Scripts/Menu/InfiniteModeNextLevelButton.cs
> +    public class InfiniteModeNextLevelButton : MonoBehaviour
doc

2022-01-10 16:42 UTC, youenPlusquellec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Mode "infini"](https://trello.com/c/MpMEtunX/82-mode-infini)

2022-01-10 20:10 UTC, Enoriz requested changes

2022-01-10 20:10 UTC, Enoriz commented on Assets/Modules/Entity/Script/SubStats/EnemyStats.cs
> +        public void Scale(int level)
doc à faire

2022-01-10 20:10 UTC, Enoriz commented on Assets/Modules/Entity/Script/SubStats/HeroStats.cs
> +        public void Scale()
doc à faire

2022-01-10 20:10 UTC, Enoriz commented on Assets/Modules/Mapping/Scripts/LevelManager.cs
> +        public void LoadRandomLevel(Action cb)
doc à faire

2022-01-10 20:10 UTC, Enoriz commented on Assets/Modules/Mapping/Scripts/LevelManager.cs
> +        public List<string> GetAllAvailableMusics()
doc à faire

2022-01-10 20:10 UTC, Enoriz commented on Assets/Modules/UI/Scripts/Manager/UIManager.cs
> +        public void HideEndGameUIElements()
doc à faire

2022-01-10 20:10 UTC, Enoriz commented on Assets/Modules/UI/Scripts/Score/ScoreManager.cs
> +        public void FinishGameReset()
doc à faire

2022-01-10 20:10 UTC, Enoriz commented on Assets/Modules/UI/Scripts/Score/UIScore.cs
> +        public void HideEndGameUIScoreElements()
doc à faire

2022-01-14 00:09 UTC, youenPlusquellec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Faire scale les statistiques des héros / ennemies en fonction du niveau.](https://trello.com/c/MvyBuvtV/105-faire-scale-les-statistiques-des-h%C3%A9ros-ennemies-en-fonction-du-niveau)

2022-01-14 10:55 UTC, merged