✨ Sound design
AlohaGames/RushTheMusic pull request #96
Opened 2022-01-14 14:47 UTC by Ailurus13

2022-01-16 20:59 UTC, DoBrcd requested changes
J'ai pas regarder toutes les classes dans le détails, c'est surtout l'implémentation que je voulais voir,
On peut rediscuter des remarques au besoin

2022-01-16 20:59 UTC, DoBrcd commented on Assets/Modules/SoundEffect/Scripts/SoundEffectManager.cs
> +
Dans cette partie, je vois un problème au fait de mettre les sons dans un container séparé : 
 - Lorsque l'objet (enemie, projectile, etc ...) va se déplacer, le son lui ne bougera pas, la spacialisation n'aura alors pas le même effet
 - Dans l'idéal il faudrait venir placer l'audio source soit en enfant de l'objet soit en component de cet objet
 - Sinon j'aime beaucoup ton implémentation

2022-01-16 20:59 UTC, DoBrcd commented on Assets/Modules/UI/Scripts/Menu/IbiscusButton.cs
> +    public class IbiscusButton : MonoBehaviour
C'est pas `HibiscusButton` ?

2022-01-26 08:03 UTC, DoBrcd commented
Des changements ici ?

2022-02-02 19:06 UTC, youenPlusquellec commented on Assets/Modules/SoundEffect/Scripts/SoundEffectManager.cs
> +        public List<AudioSource> sources;
Majuscule

2022-02-02 19:06 UTC, youenPlusquellec commented on Assets/Modules/SoundEffect/Scripts/SoundEffectManager.cs
> +        public void Pause()
Documentation partout

2022-02-02 19:06 UTC, youenPlusquellec commented on Assets/Modules/SoundEffect/Scripts/Sounds.cs
> +    [CreateAssetMenu(fileName = "Sounds", menuName = "Sounds", order = 1)]
Doc

2022-02-02 23:45 UTC, youenPlusquellec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ajout de sound design](https://trello.com/c/5tjZZTu2/92-ajout-de-sound-design)

2022-02-03 09:59 UTC, merged

2022-02-03 10:32 UTC, DoBrcd approved these changes
Je propose juste de renommer Ibiscus and Hibiscus
Sinon j'approuve

2022-02-03 10:32 UTC, DoBrcd commented on Assets/Modules/UI/Scripts/Menu/IbiscusButton.cs
> +    public class IbiscusButton : MonoBehaviour
Le nom ne devrait pas être Hibiscus ?

2022-02-03 10:32 UTC, DoBrcd commented on Assets/Modules/UI/Scripts/Menu/IbiscusButton.cs
> +    public class IbiscusButton : MonoBehaviour
Je viens de check les 2 existe autant pour moi