Adding credits
AlohaGames/RushTheMusic pull request #98
Opened 2022-01-16 01:02 UTC by zartech22

Ajout des crédits accessible à partir du menu principal :
![image](https://user-images.githubusercontent.com/1734731/149643195-4dabd7b1-6481-4c60-9870-68144a981e23.png)
Ce qui donne :
![CréditsV2](https://user-images.githubusercontent.com/1734731/149643226-4e01a971-5045-46a3-972a-04d4e6fca0a1.gif)

**Attention :** J'ai eu à gérer un merge conflict sur les fichiers suivants :
* `TheGame.unity`
* `MenuRoot.prefab`
J'ai testé, ça à l'air d'être bon... Mais sait on jamais...

De plus, je vais sûrement avoir besoin de modifier vite fait `MenuRoot.cs` pour les changements sur les boutons retours.
J'attends d'avoir des précisions sur ce point.

2022-01-17 01:19 UTC, zartech22 commented
J'ai mis à jour le code C# pour coller aux changements du bouton de retour.
J'ai également changé le listenner accroché au bouton de retour des Crédits pour coller sur le nouveau fonctionnement des boutons Retour.

Je la passe en vraie PR.

2022-01-24 18:03 UTC, youenPlusquellec requested changes
![image](https://user-images.githubusercontent.com/33334707/150838685-e2c76192-5328-4d4f-90e0-2c7215bbf6e6.png)

Je pense que ce sera bien de : 
 - Ajouter un peu plus de décalage avec les côtés (de tous les côtés pour aérer)
 - Ajouter plus d'écart entre les différentes sections
 - Plus d'écart aussi entre les titres et les textes
 - Voir s'il n'y a pas moyen de rendre le logo plus sympa avec du blanc à la place du noir ?

2022-01-24 19:36 UTC, zartech22 commented
> ![image](https://user-images.githubusercontent.com/33334707/150838685-e2c76192-5328-4d4f-90e0-2c7215bbf6e6.png)
> 
> Je pense que ce sera bien de :
> 
> * Ajouter un peu plus de décalage avec les côtés (de tous les côtés pour aérer)
> * Ajouter plus d'écart entre les différentes sections
> * Plus d'écart aussi entre les titres et les textes
> * Voir s'il n'y a pas moyen de rendre le logo plus sympa avec du blanc à la place du noir ?

Je regarde pour aérer le tout. Pour le logo, faut juste me fournir la bonne version.

2022-01-28 22:49 UTC, zartech22 commented
Voilà ce à quoi ça ressemble avec la prise en compte des retours
![v2](https://user-images.githubusercontent.com/1734731/151632275-807e502f-08eb-407c-9101-63dfcc8defca.gif)

2022-01-28 23:11 UTC, zartech22 commented
Avec le logo blanc :
![image](https://user-images.githubusercontent.com/1734731/151634147-67a506f2-9dc3-4a41-a940-3c05ce42336c.png)

2022-01-28 23:16 UTC, zartech22 commented
Avec la scrollbar en rouge
![image](https://user-images.githubusercontent.com/1734731/151634506-a8ae416c-0814-4e2e-a818-12a5cccda615.png)

2022-01-29 01:26 UTC, youenPlusquellec approved these changes
gg c jolie

2022-01-29 01:27 UTC, merged

2022-01-29 23:54 UTC, youenPlusquellec commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ajout de credits](https://trello.com/c/1jNM1lFG/121-ajout-de-credits)